// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfamuU8_pbGNKK7R0YHXR7kgrGAuiR6M',
    appId: '1:989801447738:web:3bf4c068dd6af7aee6d003',
    messagingSenderId: '989801447738',
    projectId: 'foodandfind-app',
    authDomain: 'foodandfind-app.firebaseapp.com',
    storageBucket: 'foodandfind-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-3SQxnZNMqiXb-NMrEKw9jNvhDWpqsdg',
    appId: '1:989801447738:android:ae2121bbf3b9cfeae6d003',
    messagingSenderId: '989801447738',
    projectId: 'foodandfind-app',
    storageBucket: 'foodandfind-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxO5SyQVNOhbVSBVljWUmDtLucl4I6M7s',
    appId: '1:989801447738:ios:1f5b91bcfd9bdf74e6d003',
    messagingSenderId: '989801447738',
    projectId: 'foodandfind-app',
    storageBucket: 'foodandfind-app.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxO5SyQVNOhbVSBVljWUmDtLucl4I6M7s',
    appId: '1:989801447738:ios:1f5b91bcfd9bdf74e6d003',
    messagingSenderId: '989801447738',
    projectId: 'foodandfind-app',
    storageBucket: 'foodandfind-app.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrfamuU8_pbGNKK7R0YHXR7kgrGAuiR6M',
    appId: '1:989801447738:web:934b303b6b210122e6d003',
    messagingSenderId: '989801447738',
    projectId: 'foodandfind-app',
    authDomain: 'foodandfind-app.firebaseapp.com',
    storageBucket: 'foodandfind-app.firebasestorage.app',
  );
}
